# Generated by Django 4.1.5 on 2023-01-17 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('num_tarjeta', models.CharField(max_length=20)),
                ('tipo_abono', models.CharField(choices=[('Turismo', 'Turismo'), ('Moto', 'Moto'), ('PMR', 'PMR')], default='Turismo', max_length=20)),
                ('tipo_suscripcion', models.CharField(choices=[('Mensual', 'Mensual'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], default='Mensual', max_length=20)),
                ('fecha_inicio_suscripcion', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('tarifa_minuto', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=20)),
                ('fecha_entrada', models.DateTimeField()),
                ('pin', models.CharField(max_length=6)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.cliente')),
                ('plaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.plaza')),
            ],
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_pago', models.DateTimeField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('pin', models.CharField(max_length=6)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.cliente')),
                ('plaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.plaza')),
            ],
        ),
    ]
