# Generated by Django 4.1.5 on 2023-01-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_abono',
            field=models.CharField(choices=[('Turismo', 'Turismo'), ('Moto', 'Moto'), ('PMR', 'PMR')], max_length=20, null=True),
        ),
    ]
